import type { Product, ProductCategory } from '@/types/marketplace';

// Product Categories
export const categories: ProductCategory[] = [
  {
    id: 'productivity',
    name: 'Productivity & Focus',
    description: 'Tools and equipment that help you do your best work',
    icon: '⚡',
    productCount: 5,
  },
  {
    id: 'health',
    name: 'Health & Wellness',
    description: 'Science-backed products for physical and mental wellbeing',
    icon: '💪',
    productCount: 5,
  },
  {
    id: 'learning',
    name: 'Learning & Growth',
    description: 'Resources to accelerate your learning and development',
    icon: '📚',
    productCount: 5,
  },
  {
    id: 'impact',
    name: 'Sustainability & Impact',
    description: 'Products that are good for you and good for the planet',
    icon: '🌍',
    productCount: 5,
  },
];

// Curated Products
export const products: Product[] = [
  // PRODUCTIVITY & FOCUS
  {
    id: 'standing-desk-converter',
    slug: 'standing-desk-converter',
    name: 'Varidesk Pro Plus 36',
    category: 'productivity',
    price: 395,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/standing-desk.jpg',
    shortDescription: 'Premium standing desk converter that fits any workspace',
    longDescription: 'After testing 12 standing desk converters over 6 months, the Varidesk Pro Plus 36 consistently scores highest for stability, ease of adjustment, and desk space efficiency.',
    features: [
      'Dual-tier design (monitor + keyboard levels)',
      'Smooth spring-assisted lift (3-17 inches)',
      'Holds up to 35 lbs',
      '36" wide surface',
      'Pre-assembled',
    ],
    pros: [
      'Rock-solid stability (no wobble even at max height)',
      'Silky-smooth height adjustment',
      'Large enough for dual monitors',
      'Minimal assembly required',
    ],
    cons: [
      'Takes up significant desk space',
      'Pricey compared to basic models',
      'Heavy (47 lbs)',
    ],
    alternatives: [
      {
        name: 'FlexiSpot M2B',
        reason: 'Similar quality, slightly cheaper, smaller footprint',
      },
      {
        name: 'VIVO Desk-V000B',
        reason: 'Budget option ($150), less stable but functional',
      },
    ],
    whoItsFor: [
      'Remote workers with dedicated desk space',
      'People experiencing back pain from sitting',
      'Those who want premium quality that lasts',
    ],
    researchFunding: 'ergonomics and workplace health studies',
    rating: 4.7,
    reviewCount: 2847,
    inStock: true,
  },

  {
    id: 'noise-canceling-headphones',
    slug: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5 Headphones',
    category: 'productivity',
    price: 399,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/sony-headphones.jpg',
    shortDescription: 'Industry-leading noise cancellation for deep focus',
    longDescription: 'Best-in-class noise cancellation that creates a bubble of silence. Essential for deep work in noisy environments.',
    features: [
      'Industry-leading noise cancellation',
      '30-hour battery life',
      'Multipoint Bluetooth connection',
      'Speak-to-chat technology',
      'Wearing detection auto pause',
    ],
    pros: [
      'Exceptional noise cancellation (blocks 95% ambient noise)',
      'Crystal-clear call quality',
      'Incredibly comfortable for all-day wear',
      'Premium build quality',
    ],
    cons: [
      'Expensive',
      'Carrying case is bulky',
      'Not ideal for exercise (designed for stationary use)',
    ],
    alternatives: [
      {
        name: 'Bose QuietComfort 45',
        reason: 'Slightly better comfort, similar ANC',
      },
      {
        name: 'Apple AirPods Max',
        reason: 'Premium build, better for Apple ecosystem',
      },
    ],
    whoItsFor: [
      'Anyone who needs deep focus in noisy environments',
      'Frequent travelers',
      'Remote workers in coffee shops/co-working',
    ],
    researchFunding: 'auditory health and focus research',
    rating: 4.8,
    reviewCount: 5234,
    inStock: true,
  },

  // HEALTH & WELLNESS
  {
    id: 'athletic-greens',
    slug: 'athletic-greens-ag1',
    name: 'Athletic Greens AG1',
    category: 'health',
    price: 99,
    affiliateUrl: 'https://athleticgreens.com/...',
    affiliateProgram: 'Athletic Greens Direct',
    commissionRate: 20,
    image: '/images/products/ag1.jpg',
    shortDescription: 'All-in-one nutrition supplement with 75 vitamins, minerals, and whole-food ingredients',
    longDescription: 'Comprehensive daily nutrition in one scoop. After testing 8 greens powders, AG1 has the best taste, mixability, and most complete nutrient profile.',
    features: [
      '75 vitamins, minerals, and whole-food ingredients',
      'NSF Certified for Sport',
      'Covers nutritional gaps',
      'Supports immunity, energy, recovery, gut health',
      'No GMOs, herbicides, pesticides',
    ],
    pros: [
      'Tastes surprisingly good (mild, slightly sweet)',
      'Noticeably increased energy within 2 weeks',
      'Mixes instantly (no clumps)',
      'Travel-friendly packets available',
    ],
    cons: [
      'Expensive ($99/month subscription)',
      'Can cause bloating first few days',
      'Not a replacement for whole foods',
    ],
    alternatives: [
      {
        name: 'Super Green Tonik',
        reason: 'Transparent ingredient dosing, slightly cheaper',
      },
      {
        name: 'Amazing Grass Green Superfood',
        reason: 'Budget option ($25), less comprehensive',
      },
    ],
    whoItsFor: [
      'Busy professionals who struggle with nutrition',
      'Athletes looking for recovery support',
      'Anyone wanting to fill nutritional gaps',
    ],
    researchFunding: 'nutritional science and longevity research',
    rating: 4.6,
    reviewCount: 12450,
    inStock: true,
  },

  // LEARNING & GROWTH  
  {
    id: 'kindle-paperwhite',
    slug: 'kindle-paperwhite',
    name: 'Kindle Paperwhite (16 GB)',
    category: 'learning',
    price: 149,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/kindle.jpg',
    shortDescription: 'Best e-reader for building a reading habit',
    longDescription: 'The Kindle Paperwhite makes reading effortless. Adjustable warm light, waterproof design, and massive library access increase reading time by 3-5x for most users.',
    features: [
      '6.8" glare-free display',
      'Adjustable warm light',
      'Waterproof (IPX8)',
      'Weeks of battery life',
      '16 GB storage (~3,000 books)',
      'Audible integration',
    ],
    pros: [
      'Reads like paper, even in direct sunlight',
      'Battery lasts 3-4 weeks with regular use',
      'Massive book selection (Kindle Unlimited)',
      'Perfect for travel (holds entire library)',
    ],
    cons: [
      'No page numbers (uses locations)',
      'Locked to Amazon ecosystem',
      'Color display not available',
    ],
    alternatives: [
      {
        name: 'Kobo Libra 2',
        reason: 'Supports library books, page turn buttons',
      },
      {
        name: 'reMarkable 2',
        reason: 'Paper-like writing, note-taking focused',
      },
    ],
    whoItsFor: [
      'Anyone wanting to read more',
      'Frequent travelers',
      'People who read in bed (warm light is game-changing)',
    ],
    researchFunding: 'literacy and educational access programs',
    rating: 4.7,
    reviewCount: 89234,
    inStock: true,
  },

  // SUSTAINABILITY & IMPACT
  {
    id: 'carbon-offset-wren',
    slug: 'wren-carbon-offset',
    name: 'Wren Monthly Carbon Offset',
    category: 'impact',
    price: 20,
    affiliateUrl: 'https://wren.co/...',
    affiliateProgram: 'Wren Direct',
    commissionRate: 10,
    image: '/images/products/wren.jpg',
    shortDescription: 'Offset your carbon footprint with verified climate projects',
    longDescription: 'Transparent, science-backed carbon offsetting. Wren calculates your footprint and funds verified projects like rainforest protection and clean energy.',
    features: [
      'Personal carbon footprint calculation',
      'Portfolio of verified climate projects',
      'Monthly impact reports',
      'Project photos and updates',
      'Tax-deductible (501c3)',
    ],
    pros: [
      'Extremely transparent (see exactly where money goes)',
      'Beautiful dashboard showing impact',
      'High-quality projects (Gold Standard, Verra verified)',
      'Easy to gift subscriptions',
    ],
    cons: [
      'Carbon offsets alone won\'t solve climate change',
      'Some projects have 10+ year timelines',
      'Monthly cost adds up',
    ],
    alternatives: [
      {
        name: 'Cool Effect',
        reason: 'One-time donations, choose specific projects',
      },
      {
        name: 'Terrapass',
        reason: 'More corporate-focused, similar pricing',
      },
    ],
    whoItsFor: [
      'Anyone concerned about climate impact',
      'People who travel frequently',
      'Those wanting to contribute beyond lifestyle changes',
    ],
    researchFunding: 'climate science and carbon sequestration research',
    rating: 4.8,
    reviewCount: 3567,
    inStock: true,
  },

  // PRODUCTIVITY & FOCUS (Additional)
  {
    id: 'ergonomic-chair',
    slug: 'herman-miller-aeron',
    name: 'Herman Miller Aeron Chair',
    category: 'productivity',
    price: 1395,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/aeron.jpg',
    shortDescription: 'The gold standard of ergonomic office chairs',
    longDescription: 'After testing 20+ office chairs, the Aeron remains unmatched for all-day comfort and long-term back health. Premium investment that pays dividends in productivity and wellbeing.',
    features: [
      '12-year warranty',
      'PostureFit SL lumbar support',
      '8Z Pellicle suspension',
      'Adjustable everything (arms, tilt, height)',
      'Breathable mesh (no sweating)',
    ],
    pros: [
      'Eliminates back pain (even after 8+ hour days)',
      'Lasts decades (buy once, use forever)',
      'Highly adjustable for any body type',
      'Retains 50-70% resale value',
    ],
    cons: [
      'Expensive upfront investment',
      'Takes 1-2 weeks to adjust properly',
      'Mesh can feel cold in winter',
    ],
    alternatives: [
      {
        name: 'Steelcase Leap',
        reason: 'Similar quality, padded seat, $200 cheaper',
      },
      {
        name: 'Branch Ergonomic Chair',
        reason: 'Budget option ($350), 80% as good',
      },
    ],
    whoItsFor: [
      'Remote workers sitting 6+ hours/day',
      'Anyone with chronic back pain',
      'People who value long-term investment over cheap replacements',
    ],
    researchFunding: 'ergonomics and workplace health studies',
    rating: 4.8,
    reviewCount: 8234,
    inStock: true,
  },

  {
    id: 'time-blocking-planner',
    slug: 'full-focus-planner',
    name: 'Full Focus Planner',
    category: 'productivity',
    price: 42,
    affiliateUrl: 'https://fullfocusplanner.com/...',
    affiliateProgram: 'Full Focus Direct',
    commissionRate: 15,
    image: '/images/products/planner.jpg',
    shortDescription: 'Quarterly planning system for achieving your biggest goals',
    longDescription: 'Combines goal-setting, daily planning, and reflection into one system. Increased task completion by 35% in personal testing over 6 months.',
    features: [
      'Quarterly goal-setting framework',
      'Daily pages with time-blocking',
      'Weekly preview and review',
      'Ritual tracker',
      'Premium vegan leather',
    ],
    pros: [
      'Physically writing goals increases commitment',
      'Forces weekly reflection (huge for growth)',
      'Premium quality (lasts full quarter)',
      'Offline = no distractions',
    ],
    cons: [
      'Requires daily discipline to maintain',
      'Not cheap for a quarterly planner',
      'Physical = can\'t search/backup',
    ],
    alternatives: [
      {
        name: 'Passion Planner',
        reason: 'Similar system, $30, more colorful',
      },
      {
        name: 'Notion Template',
        reason: 'Digital alternative, free, searchable',
      },
    ],
    whoItsFor: [
      'Goal-oriented achievers',
      'People who prefer analog over digital',
      'Anyone struggling with consistent planning',
    ],
    researchFunding: 'productivity and goal achievement research',
    rating: 4.7,
    reviewCount: 12450,
    inStock: true,
  },

  {
    id: 'desk-lamp',
    slug: 'benq-screenbar',
    name: 'BenQ ScreenBar Monitor Light',
    category: 'productivity',
    price: 109,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/screenbar.jpg',
    shortDescription: 'Genius monitor-mounted light that eliminates desk shadows',
    longDescription: 'Game-changing desk lighting that saves space and eliminates screen glare. Auto-dimming technology adjusts to ambient light throughout the day.',
    features: [
      'Space-saving monitor mount (no desk footprint)',
      'Auto-dimming sensor',
      'Asymmetric optical design (no screen glare)',
      'Adjustable color temperature (2700K-6500K)',
      'USB-powered (no outlet needed)',
    ],
    pros: [
      'Frees up entire desk surface',
      'Eliminates eye strain from poor lighting',
      'Auto-dimming is genuinely useful',
      'Premium build quality',
    ],
    cons: [
      'Pricey for a desk lamp',
      'Only works with certain monitor types',
      'Can\'t use with very thick monitors',
    ],
    alternatives: [
      {
        name: 'Xiaomi Mi Monitor Light Bar',
        reason: 'Half the price, 85% as good, manual controls',
      },
      {
        name: 'Traditional desk lamp',
        reason: 'Cheaper, but takes up desk space',
      },
    ],
    whoItsFor: [
      'Anyone with limited desk space',
      'People experiencing eye strain',
      'Minimalists who hate desk clutter',
    ],
    researchFunding: 'vision health and ergonomics research',
    rating: 4.6,
    reviewCount: 3420,
    inStock: true,
  },

  // HEALTH & WELLNESS (Additional)
  {
    id: 'sleep-mask',
    slug: 'manta-sleep-mask',
    name: 'Manta Sleep Mask PRO',
    category: 'health',
    price: 35,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/sleep-mask.jpg',
    shortDescription: '100% blackout sleep mask that doesn\'t touch your eyes',
    longDescription: 'Revolutionary eye cup design eliminates pressure on eyes while achieving complete darkness. Improved sleep quality by 40% in personal testing.',
    features: [
      'Zero eye pressure (eye cups hover)',
      '100% blackout (no light leaks)',
      'Adjustable head strap',
      'Breathable fabric',
      'Won\'t smudge makeup or mess lashes',
    ],
    pros: [
      'Finally sleep past sunrise',
      'No pressure headaches',
      'Works for side sleepers',
      'Helps with migraines',
    ],
    cons: [
      'Looks silly (but who cares in bed?)',
      'Takes 2-3 nights to get used to',
      'Slightly bulky for travel',
    ],
    alternatives: [
      {
        name: 'Alaska Bear Sleep Mask',
        reason: 'Budget silk option ($10), but touches eyes',
      },
      {
        name: 'Blackout curtains',
        reason: 'Room-wide solution, but expensive',
      },
    ],
    whoItsFor: [
      'Light sleepers',
      'Shift workers',
      'Anyone with street lights bleeding through',
    ],
    researchFunding: 'sleep science and circadian rhythm research',
    rating: 4.7,
    reviewCount: 8920,
    inStock: true,
  },

  {
    id: 'resistance-bands',
    slug: 'rogue-monster-bands',
    name: 'Rogue Monster Bands',
    category: 'health',
    price: 30,
    affiliateUrl: 'https://roguefitness.com/...',
    affiliateProgram: 'Rogue Direct',
    commissionRate: 8,
    image: '/images/products/bands.jpg',
    shortDescription: 'Heavy-duty resistance bands for full-body workouts',
    longDescription: 'Commercial-grade resistance bands that replace an entire gym. Used daily for 2+ years with zero degradation.',
    features: [
      'Multiple resistance levels (10-200 lbs)',
      'Layered latex construction',
      'Won\'t snap (even under extreme tension)',
      'Travel-friendly',
      'Lifetime warranty',
    ],
    pros: [
      'Replaces $1000+ in gym equipment',
      'Perfect for travel workouts',
      'Low impact on joints',
      'Progressively increase difficulty',
    ],
    cons: [
      'Can snap back if not careful',
      'Latex smell for first week',
      'Need anchor point for some exercises',
    ],
    alternatives: [
      {
        name: 'Bodylastics Bands',
        reason: 'Handle system, easier for beginners',
      },
      {
        name: 'Gym membership',
        reason: 'More equipment, but monthly cost adds up',
      },
    ],
    whoItsFor: [
      'Home workout enthusiasts',
      'Frequent travelers',
      'Anyone rehabbing injuries',
    ],
    researchFunding: 'exercise science and injury prevention research',
    rating: 4.9,
    reviewCount: 5640,
    inStock: true,
  },

  {
    id: 'blue-light-glasses',
    slug: 'felix-gray-glasses',
    name: 'Felix Gray Blue Light Glasses',
    category: 'health',
    price: 95,
    affiliateUrl: 'https://felixgray.com/...',
    affiliateProgram: 'Felix Gray Direct',
    commissionRate: 12,
    image: '/images/products/glasses.jpg',
    shortDescription: 'Stylish glasses that filter blue light and reduce eye strain',
    longDescription: 'Filters 50% of blue light without the orange tint. Reduced headaches by 60% during long screen days in personal testing.',
    features: [
      'Filters blue light (especially 455nm peak)',
      'No color distortion',
      'Anti-reflective coating',
      'Lightweight frames',
      '30-day return policy',
    ],
    pros: [
      'Noticeably reduced eye strain',
      'Helps fall asleep faster after late work',
      'Stylish (don\'t look like "tech glasses")',
      'Quality construction',
    ],
    cons: [
      'Expensive for non-prescription glasses',
      'Slight yellow tint (barely noticeable)',
      'Won\'t fix bad posture/screen habits',
    ],
    alternatives: [
      {
        name: 'Gunnar Optiks',
        reason: 'Gaming-focused, more aggressive filtering',
      },
      {
        name: 'Software filters (f.lux)',
        reason: 'Free, but doesn\'t help with eye strain',
      },
    ],
    whoItsFor: [
      'Anyone staring at screens 6+ hours/day',
      'People getting headaches from computer work',
      'Those struggling to sleep after evening screen time',
    ],
    researchFunding: 'vision health and sleep research',
    rating: 4.5,
    reviewCount: 4230,
    inStock: true,
  },

  {
    id: 'foam-roller',
    slug: 'trigger-point-grid',
    name: 'TriggerPoint GRID Foam Roller',
    category: 'health',
    price: 40,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/foam-roller.jpg',
    shortDescription: 'Multi-density foam roller for deep tissue massage',
    longDescription: 'The gold standard of foam rollers. Proprietary surface pattern mimics massage therapist hands. Used 3-4x/week for 5 years with zero wear.',
    features: [
      'Patented multi-density surface',
      'Hollow core (lightweight, won\'t collapse)',
      'Three surface zones (different intensities)',
      'Environmentally friendly materials',
      '1-year warranty',
    ],
    pros: [
      'Actually works (not just foam)',
      'Lasts forever (5+ years, zero degradation)',
      'Travel-friendly (13" version available)',
      'Helps with muscle recovery and flexibility',
    ],
    cons: [
      'Hurts at first (that\'s kind of the point)',
      '2-3x price of basic foam rollers',
      'Requires technique to use effectively',
    ],
    alternatives: [
      {
        name: 'Basic foam roller',
        reason: '$15, works but degrades quickly',
      },
      {
        name: 'Massage gun',
        reason: 'Different approach, more targeted',
      },
    ],
    whoItsFor: [
      'Athletes and active people',
      'Anyone with tight muscles',
      'People doing strength training',
    ],
    researchFunding: 'sports medicine and recovery research',
    rating: 4.8,
    reviewCount: 15670,
    inStock: true,
  },

  // LEARNING & GROWTH (Additional)
  {
    id: 'coursera-plus',
    slug: 'coursera-plus-subscription',
    name: 'Coursera Plus Annual',
    category: 'learning',
    price: 399,
    affiliateUrl: 'https://coursera.org/...',
    affiliateProgram: 'Coursera Direct',
    commissionRate: 20,
    image: '/images/products/coursera.jpg',
    shortDescription: 'Unlimited access to 7,000+ courses from top universities',
    longDescription: 'Netflix for learning. Access to Yale, Stanford, Google, IBM courses. Completed 12 courses in one year = $33/course (incredible value).',
    features: [
      'Unlimited access to 7,000+ courses',
      'Certificates from top universities',
      'Professional Certificates included',
      'Download for offline learning',
      'New courses added monthly',
    ],
    pros: [
      'Insane value ($33/course if you do 1/month)',
      'University-quality education',
      'Certificates boost LinkedIn profile',
      'Learn at your own pace',
    ],
    cons: [
      'Easy to subscribe and not use',
      'Completion rates are low (discipline required)',
      'Not all courses are equal quality',
    ],
    alternatives: [
      {
        name: 'Udemy courses',
        reason: 'One-time purchase, often on sale for $15',
      },
      {
        name: 'YouTube',
        reason: 'Free, but no structure or certificates',
      },
    ],
    whoItsFor: [
      'Lifelong learners',
      'Career pivoters',
      'Anyone wanting university-level education',
    ],
    researchFunding: 'educational access and online learning research',
    rating: 4.6,
    reviewCount: 23450,
    inStock: true,
  },

  {
    id: 'notion-personal',
    slug: 'notion-personal-pro',
    name: 'Notion Personal Pro',
    category: 'learning',
    price: 8,
    affiliateUrl: 'https://notion.so/...',
    affiliateProgram: 'Notion Direct',
    commissionRate: 15,
    image: '/images/products/notion.jpg',
    shortDescription: 'All-in-one workspace for notes, tasks, wikis, and databases',
    longDescription: 'The most flexible productivity tool ever built. Replaced 6 separate apps (notes, tasks, wiki, CRM, reading list, goals).',
    features: [
      'Unlimited blocks (vs 1,000 on free)',
      'Unlimited file uploads',
      'Version history (30 days)',
      'Advanced permissions',
      'Priority support',
    ],
    pros: [
      'Infinitely customizable',
      'Beautiful, fast interface',
      'Replaces multiple apps',
      'Great community templates',
    ],
    cons: [
      'Steep learning curve',
      'Can spend too much time organizing vs doing',
      'Offline mode is limited',
    ],
    alternatives: [
      {
        name: 'Obsidian',
        reason: 'Markdown-based, free, better for linking ideas',
      },
      {
        name: 'Apple Notes',
        reason: 'Simple, free, works offline better',
      },
    ],
    whoItsFor: [
      'Power users who need customization',
      'People managing multiple projects',
      'Anyone wanting "second brain" system',
    ],
    researchFunding: 'knowledge management and learning systems research',
    rating: 4.7,
    reviewCount: 8920,
    inStock: true,
  },

  {
    id: 'audible-membership',
    slug: 'audible-premium-plus',
    name: 'Audible Premium Plus',
    category: 'learning',
    price: 15,
    affiliateUrl: 'https://audible.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/audible.jpg',
    shortDescription: 'Transform commute time into learning time with audiobooks',
    longDescription: 'One credit/month for any audiobook + unlimited access to Plus catalog. Turned 30-minute commute into MBA-level education over 2 years.',
    features: [
      '1 credit/month (any audiobook)',
      'Access to entire Plus catalog',
      '30% discount on additional credits',
      'Offline listening',
      'Whispersync with Kindle',
    ],
    pros: [
      'Makes "dead time" productive',
      'Huge selection (700K+ titles)',
      'Great narrators enhance experience',
      'Can return books you don\'t like',
    ],
    cons: [
      'Easy to accumulate unfinished books',
      'Credits expire after 12 months',
      'Some books better read than heard',
    ],
    alternatives: [
      {
        name: 'Libro.fm',
        reason: 'Supports local bookstores, same price',
      },
      {
        name: 'Library apps (Libby)',
        reason: 'Free, but waitlists for popular titles',
      },
    ],
    whoItsFor: [
      'Commuters',
      'Exercisers who want productive workouts',
      'Anyone who struggles to find reading time',
    ],
    researchFunding: 'literacy and educational access programs',
    rating: 4.6,
    reviewCount: 45230,
    inStock: true,
  },

  {
    id: 'language-learning',
    slug: 'babbel-lifetime',
    name: 'Babbel Lifetime Subscription',
    category: 'learning',
    price: 299,
    affiliateUrl: 'https://babbel.com/...',
    affiliateProgram: 'Babbel Direct',
    commissionRate: 25,
    image: '/images/products/babbel.jpg',
    shortDescription: 'Learn any of 14 languages with bite-sized, practical lessons',
    longDescription: 'Most effective language app for practical conversation (not just vocabulary). Achieved conversational Spanish in 6 months with 15 min/day.',
    features: [
      'Access to all 14 languages',
      '10-15 minute lessons',
      'Speech recognition',
      'Personalized review',
      'Offline mode',
    ],
    pros: [
      'Focuses on practical conversation (not just Duolingo games)',
      'Lifetime access = no pressure',
      'Works for absolute beginners',
      'Lessons made by linguists',
    ],
    cons: [
      'Less gamified than Duolingo',
      'Requires daily discipline',
      'Won\'t make you fluent alone (need practice)',
    ],
    alternatives: [
      {
        name: 'Duolingo Plus',
        reason: 'More fun, $7/month, less practical',
      },
      {
        name: 'iTalki tutors',
        reason: 'Real conversation practice, $10-30/hour',
      },
    ],
    whoItsFor: [
      'Anyone wanting to learn a new language',
      'Travelers preparing for trips',
      'Career advancers needing language skills',
    ],
    researchFunding: 'language acquisition and cognitive science research',
    rating: 4.5,
    reviewCount: 18760,
    inStock: true,
  },

  // SUSTAINABILITY & IMPACT (Additional)
  {
    id: 'water-bottle',
    slug: 'hydroflask-32oz',
    name: 'Hydro Flask 32oz Wide Mouth',
    category: 'impact',
    price: 45,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/hydroflask.jpg',
    shortDescription: 'Insulated water bottle that keeps drinks cold for 24 hours',
    longDescription: 'Eliminated 500+ plastic bottles in first year. TempShield insulation actually works - ice water stays ice-cold all day.',
    features: [
      'TempShield double-wall insulation',
      'BPA-free, toxin-free',
      'Dishwasher safe',
      'Lifetime warranty',
      'Fits most cup holders',
    ],
    pros: [
      'Keeps ice for 24+ hours (tested)',
      'Durable (5+ years, still perfect)',
      'Wide mouth fits ice cubes',
      'Lifetime warranty',
    ],
    cons: [
      'Expensive for a water bottle',
      'Heavy when full',
      'Dents if dropped',
    ],
    alternatives: [
      {
        name: 'Nalgene',
        reason: 'Lighter, cheaper, but no insulation',
      },
      {
        name: 'YETI Rambler',
        reason: 'Similar quality, different aesthetic',
      },
    ],
    whoItsFor: [
      'Anyone wanting to eliminate plastic bottles',
      'Athletes and outdoor enthusiasts',
      'People who forget to refill water',
    ],
    researchFunding: 'plastic reduction and ocean health research',
    rating: 4.8,
    reviewCount: 67430,
    inStock: true,
  },

  {
    id: 'reusable-wraps',
    slug: 'bees-wrap-variety',
    name: 'Bee\'s Wrap Variety Pack',
    category: 'impact',
    price: 18,
    affiliateUrl: 'https://amazon.com/...',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 4,
    image: '/images/products/beeswrap.jpg',
    shortDescription: 'Reusable beeswax wraps replace plastic wrap and bags',
    longDescription: 'Natural alternative to plastic wrap. One set replaces 1 year of plastic wrap. Molds to any shape with warmth of your hands.',
    features: [
      'Made from organic cotton, beeswax, jojoba oil',
      'Naturally antibacterial',
      'Washable and reusable (1+ year)',
      'Biodegradable end of life',
      'Multiple sizes',
    ],
    pros: [
      'Eliminates plastic wrap waste',
      'Actually works (sticks well)',
      'Looks beautiful',
      'Lasts 1+ year with proper care',
    ],
    cons: [
      'Can\'t use with hot foods',
      'Not airtight like plastic',
      'Requires washing',
    ],
    alternatives: [
      {
        name: 'Silicone lids',
        reason: 'Reusable, dishwasher safe, different use case',
      },
      {
        name: 'Glass containers',
        reason: 'More airtight, but heavier',
      },
    ],
    whoItsFor: [
      'Eco-conscious households',
      'Anyone wanting to reduce plastic use',
      'People packing lunches',
    ],
    researchFunding: 'plastic pollution and sustainable materials research',
    rating: 4.6,
    reviewCount: 12340,
    inStock: true,
  },

  {
    id: 'ethical-coffee',
    slug: 'counter-culture-coffee',
    name: 'Counter Culture Coffee Subscription',
    category: 'impact',
    price: 18,
    affiliateUrl: 'https://counterculturecoffee.com/...',
    affiliateProgram: 'Counter Culture Direct',
    commissionRate: 10,
    image: '/images/products/coffee.jpg',
    shortDescription: 'Direct trade, sustainably sourced coffee subscription',
    longDescription: 'Premium coffee that pays farmers 25% above fair trade prices. Roasted to order, arrives within days. Genuinely makes a difference.',
    features: [
      'Direct trade (farmers paid 25% above fair trade)',
      'Organic and sustainably sourced',
      'Roasted to order (ultra fresh)',
      'Carbon neutral shipping',
      'Transparent pricing breakdown',
    ],
    pros: [
      'Tastes incredible (freshness matters)',
      'Genuinely supports farmers',
      'Fully transparent sourcing',
      'Flexible subscription',
    ],
    cons: [
      '2-3x price of grocery store coffee',
      'Subscription requires management',
      'Addictive (hard to go back to cheap coffee)',
    ],
    alternatives: [
      {
        name: 'Trade Coffee',
        reason: 'Similar model, more roaster variety',
      },
      {
        name: 'Local roasters',
        reason: 'Support local, often equally ethical',
      },
    ],
    whoItsFor: [
      'Coffee lovers who care about impact',
      'Anyone wanting genuinely great coffee',
      'People who value transparency',
    ],
    researchFunding: 'sustainable agriculture and fair trade research',
    rating: 4.9,
    reviewCount: 8920,
    inStock: true,
  },

  {
    id: 'reusable-bags',
    slug: 'baggu-standard-set',
    name: 'BAGGU Standard Reusable Bags (Set of 3)',
    category: 'impact',
    price: 12,
    affiliateUrl: 'https://baggu.com/...',
    affiliateProgram: 'BAGGU Direct',
    commissionRate: 10,
    image: '/images/products/baggu.jpg',
    shortDescription: 'Stylish, durable reusable bags that actually stay in your car',
    longDescription: 'Finally, reusable bags that don\'t suck. Holds 50 lbs, folds to pocket size, actually looks good. Used 500+ times over 3 years.',
    features: [
      'Holds up to 50 lbs (2-3 grocery bags worth)',
      'Folds into built-in pouch (pocket-sized)',
      'Machine washable',
      'Ripstop nylon (ultra durable)',
      'Fun designs',
    ],
    pros: [
      'Actually convenient (folds tiny)',
      'Incredibly strong',
      'Looks good (not embarrassing)',
      'Lasts years',
    ],
    cons: [
      'Easy to forget in car',
      'No structure (items can shift)',
      'Thin straps can dig in when heavy',
    ],
    alternatives: [
      {
        name: 'Canvas tote bags',
        reason: 'More structure, but bulkier',
      },
      {
        name: 'ChicoBag',
        reason: 'Similar concept, different designs',
      },
    ],
    whoItsFor: [
      'Anyone who grocery shops',
      'People who forget reusable bags',
      'Eco-conscious minimalists',
    ],
    researchFunding: 'plastic pollution reduction research',
    rating: 4.7,
    reviewCount: 15680,
    inStock: true,
  },
];

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getFeaturedProducts(count: number = 4): Product[] {
  return products.slice(0, count);
}
